.travis.yml
- Add slack notifications for Travis CI
=> Add slack notifications for Travis CI

.travis.yml, README.md
=> Tets slack

.travis.yml, ci/test_candidate_pr.sh, ci/test_chart.sh
- Added tests for PRs from fork to candidate branch
* [] Have you followed the guidelines in our [Contributing document](CONTRIBUTING.md)?
=> Add test for PRs

.travis.yml, ci/test_candidate_pr.sh, ci/test_chart.sh
=> Add test for PRs (#46)

CONTRIBUTING.md
=> Add to contributing.md rules for external users

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/configmap_genesis_template.yaml, stable/autonity-network/values.yaml
- Add Tendermint consensus algorithm (default)
Issue #51
=> [autonity-network] Tendermint consensus algorithm

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml, stable/autonity-demo/values.yaml
- Up version to autonity-network-0.3.0 (Add Tendermint consensus algorithm by default)
Issue #51
=> Add Tendermint consensus to genesis.json

.gitignore, stable/autonity-network/.helmignore, stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/README.md, stable/autonity-network/templates/NOTES.txt, stable/autonity-network/templates/configmap_nginx.yaml, stable/autonity-network/templates/deployments_validators.yaml, stable/autonity-network/templates/services_validators.yaml, stable/autonity-network/values.yaml
- http basic auth support for autonity RPC
https://github.com/clearmatics/charts/issues/6
=> [autonity network] Release 0.3.1 http basic auth for RPC

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/README.md, stable/autonity-network/templates/NOTES.txt, stable/autonity-network/templates/configmap_nginx.yaml, stable/autonity-network/templates/deployments_observers.yaml, stable/autonity-network/templates/deployments_validators.yaml, stable/autonity-network/templates/secret_autonity_https.yaml, stable/autonity-network/values.yaml
* https support for autonity RPC
Issue: https://github.com/clearmatics/charts/issues/6
=> [autonity-network] Release 0.3.3 Add https for RPC

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/values.yaml
- autonity to dev-v0.1.5, autonity-init to v0.0.8
=> Update autonity to dev-v0.1.5

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/deployments_observers.yaml, stable/autonity-network/templates/deployments_validators.yaml, stable/autonity-network/templates/storage_class.yaml, stable/autonity-network/values.yaml
- Add AWS of GCP persistant storage
Issue #64
=> [autonity-network] v0.3.6

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/values.yaml
- Up docker images:
- autonity to v0.1.6
- autonity-init to v0.1.1
Issue #66
=> [autonity-network] Update autonity up to v0.1.6

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml, stable/autonity-demo/templates/NOTES.txt, stable/autonity-network/templates/NOTES.txt
- Up version to `autonity-network-0.3.7`
=> [autonity-demo] Release v0.4.8

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/files/grafana/dashboards/autonity.json, stable/autonity-demo/requirements.yaml, stable/autonity-demo/templates/prometheus_configmap.yaml
- Up version to autonity-network-1.0.0
Issue #62
=> [autonity-demo] Support new metrics with auutonity-network-1.0.0

stable/autonity-demo/values.yaml, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/deployments_observers.yaml, stable/autonity-network/templates/deployments_validators.yaml, stable/autonity-network/templates/init_job01_ibft_keys_generator.yaml, stable/autonity-network/templates/init_job02_ibft_genesis_configurator.yaml, stable/autonity-network/templates/services_observers.yaml, stable/autonity-network/templates/services_validators.yaml, stable/autonity-network/templates/storage_class.yaml, stable/autonity-network/values.yaml
enable a list of ip's to be passed in via values.yaml and used for static public ip addresses
=> Consume loadbalancers from terraform

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/configmap_genesis_template.yaml
- Fixed `genesis.json` default options
=> [autonity-network] Release 1.1.1. Fix genesis.json

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/configmap_genesis_template.yaml
- Add `petersburgBlock` to `genesis.json`
=> [autonity-network] Release 1.1.2

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml
- update autonity-network to 1.1.2
=> [autonity-demo] Release 1.0.2

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml
- update autonity-network to 1.2.0
=> [autonity-demo] Release 1.0.3

stable/autonity-network/Chart.yaml, stable/autonity-network/templates/init_job02_ibft_genesis_configurator.yaml
update chart to feed genesis job with names rather than ip addresses (if provided)
=> update chart to feed genesis job with names rather than ip addresses

stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/init_job02_ibft_genesis_configurator.yaml
update autonitydemo to use autonity-network 1.3.0
=> Autonity-demo to use autonity-network 1.3.0

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/configmap_nginx.yaml
=> [autonity-network] Release 1.3.1

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml
update to autonity-network-1.3.1
=> [autonity-demo] Release 1.0.5

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/deployments_observers.yaml, stable/autonity-network/templates/deployments_validators.yaml, stable/autonity-network/values.yaml
- autonity option `NetworkID`
Issue #78
=> [autonity-network] Release 1.3.2

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/RBAC.yaml, stable/autonity-network/templates/configmap_operator_treasury.yaml, stable/autonity-network/templates/secret_operator_treasury.yaml, stable/autonity-network/values.yaml
- Refactoring treasure --> treasury
Issue #86
=> [autonity-network] Release 1.3.4

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml
=> Autonity demo 1.0.7 update autonity-network

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/README.md, stable/autonity-network/templates/NOTES.txt, stable/autonity-network/templates/configmap_genesis_template.yaml, stable/autonity-network/templates/init_job02_ibft_genesis_configurator.yaml, stable/autonity-network/values.yaml
- autonity to `v0.2.0`
Issue #81
=> [autonity-network] Release 1.5.0

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/values.yaml
=> [autonity-network] Release v1.5.1

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml
Fix version mistake https://github.com/clearmatics/charts-ose/pull/92/files to release
=> [autonity-demo] Release v1.0.8

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/services_observers.yaml, stable/autonity-network/templates/services_validators.yaml, stable/autonity-network/values.yaml
allow autonity network to define firewall rules
=> Autonity network

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml
allow autonity network to define firewall rules
=> up autonity-network to 1.5.2

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/requirements.yaml, stable/autonity-demo/values_gke_persistent_storage.yaml, stable/autonity-network/README.md
- Up version to prometheus-9.1.1
- Update helm grafana to 3.8.15 (grafana v6.1.6 ==> v6.3.5)
- add example file with values for GKE persistent storage installathion
Issue #99
=> [autonity-demo] Release v1.0.10

stable/autonity-demo/CHANGELOG.md, stable/autonity-demo/Chart.yaml, stable/autonity-demo/README.md, stable/autonity-demo/files/grafana/dashboards/autonity.json, stable/autonity-network/README.md
- Update grafana dashboard
- fix readme
=> [autonity-demo] Release 1.0.11

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/docs/workshop_initial_ceremony.md, stable/autonity/docs/workshop_join_new_node.md, stable/autonity/templates/NOTES.txt
- Fixed Notes to get contract address
- Fixed workshop docs
Issue #106
=> [autonity] Release 0.0.5

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/configmap_genesis_template.yaml, stable/autonity-network/templates/deployments_observers.yaml, stable/autonity-network/templates/deployments_validators.yaml, stable/autonity-network/templates/init_job02_ibft_genesis_configurator.yaml, stable/autonity-network/templates/services_observers.yaml, stable/autonity-network/templates/services_validators.yaml, stable/autonity-network/values.yaml
- `tendermint` to API
- Fixed wrong key for `operator` in genesis.json
- requirements to `helm` > v2.15.0
Issue #110
Issue #113
=> [autonity-network] Release 1.5.3

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/docs/workshop_join_new_node.md, stable/autonity/genesis.yaml
- Workshop changes
https://github.com/clearmatics/www-devops/issues/41
=> [autonity] Release 1.0.2

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/docs/workshop_join_new_node.md
*  Workshops update
Issue #128
=> [autonity] Release 1.0.3

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/values.yaml
- Autonity to v0.3.0
- Autonity-init to v1.0.4 (based on autonity v0.3.0)
=> [autonity-network] Release 1.5.7 (based on autonity to 0.3.0)

.travis.yml, ci/test_chart.sh, stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/services_autonity_node.yaml, stable/autonity/values.yaml
- Support static GCP public IP for p2p
Issue: https://github.com/clearmatics/charts-ose/issues/134
=> [autonity] Release v1.0.5

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/deployments_autonity_node.yaml, stable/autonity/values.yaml
* Support nodeSelector for GKE
Issue: https://github.com/clearmatics/charts-ose/issues/136
=> Support nodeSelector for gke

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/storage_class.yaml
=> [autonity] Change Volume Binding Mode from Immediate to --> WaitForFirstConsumer

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/secret_autonity_https.yaml
- Fix bug with RPC https service
=> [autonity] Fix bug with RPC https service

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/NOTES.txt, stable/autonity/templates/services_autonity_node.yaml
- Fix `public-rpc` port nombers
Issue: #142
=> [autonity] Release 1.0.10

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/deployments_autonity_node.yaml, stable/autonity/templates/services_autonity_node.yaml, stable/autonity/values.yaml
* Updated autonity imgs Issue: [Multiply TYPE declaration for Prometheus metrics](https://github.com/clearmatics/autonity/issues/372)
* Fixed metrics ports exposing
=> [autonity] Release v1.0.10. Fix prometheus metrics

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/values.yaml
* Updated autonity imgs to `dev-0.3.0-fix2` Issue: [Multiply TYPE declaration for Prometheus metrics](https://github.com/clearmatics/autonity/issues/372)
* Fixed metrics ports exposing
=> [autonity] Release 1.0.12 Fix prometheus fix

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/deployments_autonity_node.yaml
* Fix Telegraf docker image vars
=> [autonity] Release 1.0.14

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/README.md, stable/autonity/templates/configmap_telegraf.yaml, stable/autonity/values.yaml
- Rollback to InfluxDB v1.0 support
- telegraf updated to 1.13.2-alpine
Issue #153
=> [autonity] Release 1.1.0

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/configmap_telegraf.yaml, stable/autonity/templates/deployments_autonity_node.yaml
* Change telegraf metrics tag `clent_name` ==> `afnc_name`
Issue #156
=> [autonity] Release 1.1.1

.github/PULL_REQUEST_TEMPLATE.md, stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/deployments_autonity_node.yaml, stable/autonity/values.yaml
Adding node-selector feature for aws.
=> [autonity] Release 1.1.2

.travis.yml
This adds new user (raj-shekhar1) to travis config to allow release charts to the repo.
=> Adding new sender in the travis config

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/values.yaml
- Autonity to dev-0.3.2
- Add Telegraf and IndluxDB support
=> [autonity-network] Release dev-0.3.2

stable/autonity/CHANGELOG.md, stable/autonity/Chart.yaml, stable/autonity/templates/deployments_autonity_node.yaml
- Added admin flag in the arguments for the Blockchain Explorer features.
=> [autonity] Release 1.1.3

stable/autonity-network/CHANGELOG.md, stable/autonity-network/Chart.yaml, stable/autonity-network/templates/configmap_genesis_template.yaml, stable/autonity-network/templates/deployments_observers.yaml, stable/autonity-network/templates/deployments_telepresence.yaml, stable/autonity-network/templates/deployments_validators.yaml, stable/autonity-network/values.yaml
=> [autonity-network] release 1.6.0
